sudo: required
services:
        - docker
          
          
before_install:
        - docker build -t subham03/docker-react_new -f Dockerfile.dev .

script:
        - docker run subham03/docker-react_new npm run test -- --coverage 
